AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false
  Exclude:
    - "vendor/**/*"
    - "bin/*"
    - "*.gemspec"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/MethodLength:
  Max: 15

# We intentionally memoize @object_was in save_for_beacon
Naming/MemoizedInstanceVariableName:
  Enabled: false
